### ISSUE TITLE
How to Created an Custom Converter for particular DataType (For ex: BigDecimal)?

### ISSUE THREAD

**Issue by kailashkolluru-mpokket** [aerospike-community/spring-data-aerospike-demo#125]

**Comment by agrgr** [comment]
Hello @kailashkolluru-mpokket,

Spring Data Aerospike already has built-in default converters for BigDecimal.
If you need some specific [custom converter](https://docs.spring.io/spring-data/jpa/reference/data-commons/custom-conversions.html), look at examples in `AerospikeConfiguration` class (`customConverters()` method). Basically it is needed to use `ReadingConverter` or `WritingConverter` annotation, implement `Converter` for specific types and override the `convert()` method.
